// Generated by CoffeeScript 1.3.1
(function() {
  var S;

  S = require("./scheem");

  console.log(S);

  console.log(S.runScheem("5"));

  console.log(S.runScheem("(* 5 20)"));

  console.log(S.runScheem("(begin (define x (* 3 10)) (* 5 x))"));

}).call(this);
